#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         	2
bspc config window_gap		 	10
bspc config split_ratio          	0.5

bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config paddingless_monocle  	true
bspc config single_monocle 	  	false
bspc config focus_follows_pointer 	true

bspc config focused_border_color 	'#4F8CAF'
bspc config normal_border_color		'#121213'
bspc config active_border_color		'#5498BB'
bspc config presel_feedback_color	'#3B6B97'

bspc wm --adopt-orphans

bspc rule -a Screenkey manage=off

## Autostart

# dunst
if [[ `pidof dunst` ]]; then
	pkill dunst
fi
dunst -config ~/.config/dunst/dunstrc &
